sv:
	/usr/lib/jvm/jdk-11.0.5/bin/java -classpath /home/linux/Documents/GIT/SD/target/classes:/home/linux/.m2/repository/mysql/mysql-connector-java/8.0.18/mysql-connector-java-8.0.18.jar:/home/linux/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar server.Server
cv:
	/usr/lib/jvm/jdk-11.0.5/bin/java -classpath /home/linux/Documents/GIT/SD/target/classes:/home/linux/.m2/repository/mysql/mysql-connector-java/8.0.18/mysql-connector-java-8.0.18.jar:/home/linux/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar client.Client
