CREATE TABLESPACE music_tables DATAFILE 'music_files_01.dbf' SIZE 200m;

CREATE USER music IDENTIFIED BY "music2020" DEFAULT TABLESPACE music_tables QUOTA UNLIMITED ON music_tables;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO music;